### ISSUE TITLE
Models using a standard GP with a continuous covariate fails

### ISSUE THREAD

**Issue by slhogle** [jtimonen/lgpr#20]
**Environment**
```
lgpr v1.0.12
rstantools 2.0.0
rstan 2.21.1
R 4.0.2
```

**Describe the bug**
Models using a standard GP with a continuous covariate fails

**To Reproduce**

```
fit <- lgp(y ~ gp(age) + zs(id)*gp(age) + gp(blood) + zs(sex)*gp(age) + gp_vm(dis_age),
             testdata_001,
             likelihood = "gaussian",
             refresh = 10,
             iter = 1000, 
             chains = 4,
             cores = 4,
             control = list(adapt_delta = 0.99),
             save_warmup = FALSE,
             verbose = T)


t <- seq(0, 36, by = 1)
x_pred <- new_x(testdata_001, t)
p <- pred(fit, testdata_001, reduce = mean)
plot_pred(fit, x = x_pred, pred = p, t_name="age", group_by="id")
```

`Error in data.frame(..., check.names = FALSE) : 
  arguments imply differing number of rows: 148, 24`

**Expected behavior**
plot_pred and plot_components should work here

**Additional context**
I can't get this to work with `plot_f.create.df_line()` either. Not sure if this is a user error or a bug - appreciate any help. thanks!

**Comment by jtimonen** [comment]
When calling `plot_pred()`, your `pred` argument contains predictions only at the data points, so you should not be giving the `x_pred` argument. If you want to plot predictions at test points `x_pred`, then you should use the same `x_pred` argument for both `pred()` and `plot_pred()` here. And in this case, you cannot use `new_x()` to compute the `x_pred` argument, because it cannot decide for you what value `blood` should have at the test points. If you really want to compute out-of-sample predictions for a model like this, then you should define the test points `x_pred` yourself and it should have all the same variables as `data`.

So what happens in your example is that on line 

`x_pred <- new_x(testdata_001, t)`

you are creating a data frame of test points, but `x_pred` will only contain variables `id`, `age` and `sex`. If you did

`x_pred <- new_x(testdata_001, t, x_ns = "dis_age")`

you would also get the values of dis_age at the test points. This works because  dis_age is derived from age. However, for a generic continuous variable like `blood` there is no way of knowing what its values should be given that we know `age`.

**Comment by jtimonen** [comment]
Thanks for the report. It triggered the following improvement ideas:


1. Here if you tried give your incomplete `x_pred` to `pred()`, it would say

```
 Error in check_in_data(name, data) : 
  The variable 'blood' not found in <data>!  Found data columns = {id, age, sex}. 
```

even though it should be saying that `blood` is not found in the `x` argument of `pred()`. So this message should be improved.

2. `plot_pred()` should give a more informative error if `x_pred` is not the same `x_pred` that was used to compute `pred`

**Comment by slhogle** [comment]
thanks! I realized my error a little while after posting the issue. It's actually fairly obvious (if I would have thought harder about it at the time) that you can't make out-of-sample predictions in this context for a continous indepeddent variable GP that isn't time/age... 

Still, a more informative error message could be helpful here because I didn't realize what was going on until I saw that there was  `length(seq(0, 36, by = 1))` * 4 individuals = 148 out-of-sample predictions in the x_pred while there are `nrow(testdata_001)=24` data points. That made me realize that I was only getting in-sample predictions at the data points for one of the variables (in this case blood).

I agree that a more specific error message could have been helpful

also the section - https://jtimonen.github.io/lgpr-usage/tutorials/basic.html#7_Additional_notes - touches on this - sort of.

sorry for the false bug report
